version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # Worker API
      - "9001:9001"  # Web Interface
    environment:
      - SERVER_HOST=0.0.0.0
    restart: always

  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=9000
    depends_on:
      - server
    restart: always

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=9000
    depends_on:
      - server
    restart: always 