[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
buildCommand = "echo 'Starting build...' && ls -la"

[deploy]
startCommand = "/bin/bash -c 'cd /app/build && ./server'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[ports]
http = "9001"
worker = "9000"

[deploy.variables]
DEBUG = "true" 