services:
  - type: web
    name: web-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    region: singapore
    plan: free
    numInstances: 1
    envVars:
      - key: DEBUG
        value: "true"
      - key: PORT
        value: "9001"
    ports:
      - port: 9001
        protocol: http
      - port: 9000
        protocol: tcp
    domains:
      - distributed-web-scrapper-and-crawler-c.onrender.com 