name: Deploy Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-workers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker-count: [3, 4, 5]  # Deploy 3 additional workers
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push worker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.worker
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-scraper-worker:latest
    
    - name: Deploy worker to Railway
      uses: railwayapp/cli/action@v1
      with:
        command: up
        environment: ${{ matrix.worker-count }}
        project: ${{ secrets.RAILWAY_PROJECT_ID }}
        token: ${{ secrets.RAILWAY_TOKEN }} 